# Cloudflare Pages配置文件
name = "nyt-connections-helper"
compatibility_date = "2023-10-30"

# 定时触发配置
[triggers]
crons = ["0 1 * * *"]  # 每天UTC 01:00执行

# KV存储绑定
[[kv_namespaces]]
binding = "CONNECTIONS_KV"
id = "7d3ae7d7dd4d4f6b33ad94cc082c7b"

# 环境变量
[vars]
ENVIRONMENT = "production"