name = "nyt-connections-helper"
compatibility_date = "2024-08-28"
pages_build_output_dir = "."

[env.production]
name = "nyt-connections-helper"

[[env.production.kv_namespaces]]
binding = "CONNECTIONS_KV"
id = "7d0ba7d76b4946f5b33bd584bc082c7b"

[env.production.vars]
ENVIRONMENT = "production"
SITE_URL = "https://nyt-connections-helper.pages.dev"
CRON_SECRET = "nyt-helper-secret-2025"