# Cloudflare Pages配置文件
name = "nyt-connections-helper"
compatibility_date = "2023-10-30"

# 定时触发配置
[triggers]
crons = ["20 4 * * *"]  # 每天UTC 04:20执行 (北京时间12:20)

# KV存储绑定
[[kv_namespaces]]
binding = "CONNECTIONS_KV"
id = "7d3ae7d7dd4d4f6b33ad94cc082c7b"

# 环境变量
[vars]
ENVIRONMENT = "production"