name = "nyt-connections-helper"
compatibility_date = "2024-01-01"

[env.production]
name = "nyt-connections-helper"

[[env.production.routes]]
pattern = "*"
zone_name = "your-domain.com"  # 替换为你的域名，或删除这部分使用 .pages.dev 域名