name: Daily NYT Connections Update
# Manual trigger test

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  update-puzzle:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Daily Update
        run: |
          curl -X POST https://nyt-connections-helper.pages.dev/scheduled \
            -H "Content-Type: application/json" \
            -d '{"action":"daily-update","secret":"${{ secrets.CRON_SECRET }}"}'